#ifndef CONFIGS_SIPEED_MAIX_H
#define CONFIGS_SIPEED_MAIX_H

#include <linux/sizes.h>

#define CONFIG_SYS_LOAD_ADDR 0x80000000
#define CONFIG_SYS_INIT_SP_ADDR 0x805FFFFF
#define CONFIG_SYS_MALLOC_LEN SZ_8M
#define CONFIG_SYS_CACHELINE_SIZE 32

#endif /* CONFIGS_SIPEED_MAIX_H */
